"""Synchronized tactical review widgets, extending the existing seek/draw controls."""
import html


def section(tactics) -> str:
    """Render focused tactical controls without replacing existing report sections."""
    if not tactics:return ''
    comparison=[]
    for team,facts in tactics['summary']['phase_comparison'].items():
        p,d=facts['possessing'],facts['defending']
        text=f"{team}: {p['samples']} possession / {d['samples']} defending samples. "
        if facts['comparison_available']:
            text+=f"Mean outfield width {p['mean_width_m']:.1f} / {d['mean_width_m']:.1f} m; difference {facts['possession_minus_defending_width_m']:+.1f} m."
        else:text+='Insufficient observations for a possession-versus-defending width comparison.'
        comparison.append('<p>'+html.escape(text)+'</p>')
    return '''<h2>Tactical state</h2><p>Deterministic geometric estimates, sampled at '''+str(tactics['summary']['sample_hz'])+''' Hz. Goalkeepers are excluded from shape and ball-relative counts; local pressure includes them. Unknown states mean insufficient evidence.</p>
<label><input id="tactical-centroids" type="checkbox" checked> Team centroids on pitch</label><p id="tactical-status"></p><p id="tactical-pressure"></p><p id="tactical-formation"></p>
<h3>How does team shape change?</h3><label>Metric <select id="tactical-metric"><option value="width_m">Width (m)</option><option value="depth_m">Depth (m)</option><option value="compactness_m">RMS compactness (m)</option></select></label><p>Click this chart to seek the video and pitch. The vertical line marks the current time; gaps indicate unavailable shape.</p><canvas id="tactical-chart" width="840" height="230" style="background:white;max-width:100%"></canvas>
'''+'<h4>Whole-recording possession versus defending samples</h4>'+''.join(comparison)+'''<details><summary>Pressure over time</summary><img src="tactical_pressure.png" alt="Observed proximity and sustained closing-pressure evidence"></details>
<h3>Who connects most frequently?</h3><p>Transfer Network: directed completed observable transfers, including movements that may not be intentional passes.</p>
<label>Team <select id="network-team"><option value="left">Left</option><option value="right">Right</option></select></label> <label>Window <select id="network-window"><option value="rolling">Trailing window at current video time</option><option value="full">Whole recording (includes later transfers)</option></select></label><p id="network-status"></p><canvas id="network-chart" width="840" height="360" style="background:#edf5ee;max-width:100%"></canvas>
<h3>When did persistent tactical states change?</h3><div id="tactical-timeline" style="max-height:180px;overflow:auto"></div><p><a href="tactical_states.csv">Tactical samples</a> · <a href="tactical_events.json">Tactical events</a> · <a href="transfer_network.json">Transfer networks</a> · <a href="tactical_summary.json">Definitions, thresholds and quality</a> · <a href="pre_event_evidence.json">Pre-event evidence</a></p>'''


def script() -> str:
    """Use the existing seek/draw functions for all tactical interactions."""
    return r'''
const tacticalData=data.intelligence.tactics;
const tacticalStatus=document.getElementById('tactical-status');
const networkTransfers=data.intelligence.events.events.filter(e=>e.type==='PASS_COMPLETED');
function teamColor(team){return data.sideColors[team==='left'?'0':'1']===0?'#3677c9':'#d64b4b';}
function tacticalSample(t){if(!tacticalData?.states.length)return null;const states=tacticalData.states;let lo=0,hi=states.length;while(lo<hi){const mid=Math.floor((lo+hi)/2);if(states[mid].timestamp<=t+1e-8)lo=mid+1;else hi=mid;}return lo?states[lo-1]:null;}
function drawShapeChart(t){const canvas=document.getElementById('tactical-chart');if(!canvas)return;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,metric=document.getElementById('tactical-metric').value,states=tacticalData.states;const duration=(data.frames-1)/data.fps;let max=1;for(const s of states)for(const team of ['left','right'])if(s.teams[team][metric]!==null)max=Math.max(max,s.teams[team][metric]);max*=1.1;c.clearRect(0,0,w,h);const x=t=>40+t/Math.max(duration,.04)*(w-60),y=v=>h-25-v/max*(h-50);c.strokeStyle='#aab3bf';c.strokeRect(40,20,w-60,h-45);for(const team of ['left','right']){c.strokeStyle=teamColor(team);c.beginPath();let active=false;for(const s of states){const value=s.teams[team][metric];if(value===null){active=false;continue;}if(!active)c.moveTo(x(s.timestamp),y(value));else c.lineTo(x(s.timestamp),y(value));active=true;}c.stroke();c.fillStyle=teamColor(team);c.fillText(team,team==='left'?50:120,15);}c.strokeStyle='#111';c.beginPath();c.moveTo(x(t),20);c.lineTo(x(t),h-25);c.stroke();c.fillStyle='#233044';c.fillText('0',10,h-25);c.fillText(max.toFixed(1)+' m',2,25);c.fillText(t.toFixed(2)+' s',Math.min(w-65,x(t)+3),h-5);}
function networkAt(t){const team=document.getElementById('network-team').value;if(document.getElementById('network-window').value==='full')return {edges:tacticalData.network.full.edges.filter(e=>e.team===team),nodes:tacticalData.network.full.nodes.filter(n=>n.team===team),full:true};const edges=new Map(),nodes=new Map(),window=tacticalData.config.network_window_seconds;for(const e of networkTransfers){if(e.team!==team||e.timestamp>t+1e-8||e.timestamp<=t-window)continue;const key=e.player_id+':'+e.receiver_id;const edge=edges.get(key)??{sender_id:e.player_id,receiver_id:e.receiver_id,transfer_count:0};edge.transfer_count++;edges.set(key,edge);for(const [id,x,y] of [[e.player_id,e.metrics.start_x_m,e.metrics.start_y_m],[e.receiver_id,e.metrics.end_x_m,e.metrics.end_y_m]]){if(x===undefined||y===undefined)continue;const node=nodes.get(id)??{player_id:id,x:0,y:0,count:0};node.x+=x;node.y+=y;node.count++;nodes.set(id,node);}}return {edges:[...edges.values()],nodes:[...nodes.values()].map(n=>({player_id:n.player_id,mean_x_m:n.x/n.count,mean_y_m:n.y/n.count})),full:false};}
function drawNetwork(t){const canvas=document.getElementById('network-chart');if(!canvas)return;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,network=networkAt(t),team=document.getElementById('network-team').value;c.clearRect(0,0,w,h);c.strokeStyle='#68926c';c.strokeRect(25,20,w-50,h-40);const x=v=>25+v/105*(w-50),y=v=>20+v/68*(h-40),nodes=new Map(network.nodes.map(n=>[n.player_id,n]));for(const edge of network.edges){const a=nodes.get(edge.sender_id),b=nodes.get(edge.receiver_id);if(!a||!b||a.mean_x_m===null||b.mean_x_m===null)continue;const ax=x(a.mean_x_m),ay=y(a.mean_y_m),bx=x(b.mean_x_m),by=y(b.mean_y_m),angle=Math.atan2(by-ay,bx-ax),tx=bx-12*Math.cos(angle),ty=by-12*Math.sin(angle);c.strokeStyle=teamColor(team);c.lineWidth=1+Math.min(edge.transfer_count,6);c.beginPath();c.moveTo(ax,ay);c.lineTo(tx,ty);c.stroke();c.beginPath();c.moveTo(tx,ty);c.lineTo(tx-8*Math.cos(angle-.5),ty-8*Math.sin(angle-.5));c.moveTo(tx,ty);c.lineTo(tx-8*Math.cos(angle+.5),ty-8*Math.sin(angle+.5));c.stroke();c.fillStyle='#233044';c.fillText(String(edge.transfer_count),(ax+bx)/2,(ay+by)/2);}c.lineWidth=2;for(const node of network.nodes){if(node.mean_x_m===null||node.mean_y_m===null)continue;c.fillStyle=teamColor(team);c.beginPath();c.arc(x(node.mean_x_m),y(node.mean_y_m),8,0,Math.PI*2);c.fill();c.fillStyle='#17283b';c.fillText('Player '+node.player_id,x(node.mean_x_m)+10,y(node.mean_y_m)-5);}document.getElementById('network-status').textContent=team+' · '+network.edges.reduce((sum,e)=>sum+e.transfer_count,0)+' completed observable transfers · '+(network.full?'whole recording, including later outcomes':'trailing '+tacticalData.config.network_window_seconds+' seconds up to '+t.toFixed(2)+'s')+'. Node positions average observed transfer endpoints.';}
function updateTactics(t){if(!tacticalData||!tacticalStatus)return;const s=tacticalSample(t);if(!s)return;tacticalStatus.textContent=['left','right'].map(team=>{const v=s.teams[team];return team+': '+v.phase+', '+v.block+' block; '+v.players+' observed '+(v.goalkeeper_excluded?'outfield ':'')+'players'+(v.width_m===null?' (shape unavailable)':' · centroid ('+v.centroid_x_m.toFixed(1)+', '+v.centroid_y_m.toFixed(1)+') m');}).join(' | ')+(s.centroid_distance_m===null?'':' | centroid separation '+s.centroid_distance_m.toFixed(1)+' m');const p=s.pressure;document.getElementById('tactical-pressure').textContent=p.carrier_id===null?'Carrier pressure unavailable.':'Player '+p.carrier_id+' · nearest observed defender '+(p.nearest_defender_distance_m===null?'unavailable':p.nearest_defender_distance_m.toFixed(1)+' m')+' · '+p.defenders_within_local+' opponents within '+tacticalData.config.pressure_local_radius_m+' m · '+(p.closing_defenders??'unavailable')+' closing · '+(p.sustained_press?'sustained pressure estimate':p.press_candidate?'pressure candidate':'local proximity only')+' · observed '+p.available_defenders+'/'+p.expected_defenders+' defenders.';if(s.ball_relative.attacking_ahead!==null)document.getElementById('tactical-pressure').textContent+=' Outfield ahead / behind ball: '+s.ball_relative.attacking_ahead+' / '+s.ball_relative.attacking_behind+'; observed goal-side defenders: '+s.ball_relative.defenders_goal_side+'.';document.getElementById('tactical-formation').textContent=['left','right'].map(team=>{const v=s.teams[team];return team+' estimated formation: '+v.formation+(v.formation_reason?' ('+v.formation_reason.replaceAll('_',' ')+')':' · fit RMSE '+v.formation_fit_rmse_m?.toFixed(1)+' m');}).join(' | ');if(document.getElementById('tactical-centroids').checked){for(const team of ['left','right']){const v=s.teams[team];if(v.centroid_x_m===null)continue;ctx.strokeStyle=teamColor(team);ctx.lineWidth=3;ctx.strokeRect(X(v.centroid_x_m)-7,Y(v.centroid_y_m)-7,14,14);ctx.lineWidth=2;}}drawShapeChart(t);drawNetwork(t);const timeline=document.getElementById('tactical-timeline');let nearest=null,distance=Infinity;for(const button of timeline.children){button.style.outline='';const delta=Math.abs(Number(button.dataset.time)-t);if(delta<distance){distance=delta;nearest=button;}}if(nearest)nearest.style.outline='2px solid #1558b0';}
if(tacticalData&&tacticalStatus){const timeline=document.getElementById('tactical-timeline');for(const event of tacticalData.events){const button=document.createElement('button');button.dataset.time=String(event.timestamp);button.style.margin='4px';button.textContent=event.timestamp.toFixed(2)+'s · '+event.team+' · '+event.type.replaceAll('_',' ');button.addEventListener('click',()=>seek(event.timestamp));timeline.appendChild(button);}for(const id of ['tactical-centroids','tactical-metric','network-team','network-window'])document.getElementById(id).addEventListener('change',()=>draw(Number(slider.value)));document.getElementById('tactical-chart').addEventListener('click',event=>{const canvas=document.getElementById('tactical-chart'),rect=canvas.getBoundingClientRect(),px=(event.clientX-rect.left)*canvas.width/rect.width;seek(Math.max(0,Math.min((data.frames-1)/data.fps,(px-40)/(canvas.width-60)*(data.frames-1)/data.fps)));});}
'''
